SELECT T0."ItemCode"
	,T0."ItemName"
	,T2."Name"
	,T3."NcmCode"
	,T0."SalUnitMsr"
	,T0."U_ProdCodBarras"
	,T0."U_ProdAltura"
	,T0."U_ProdLargura"
	,T0."U_ProdComprimento"
	,T0."U_EmbCodBarras"
	,T0."U_EmbAltura"
	,T0."U_EmbLargura"
	,T0."U_EmbComprimento"
	,T0."U_EmbPeso"
	,T0."U_EmbPesoLiq"
	,T0."U_InnerCodBarras"
	,T0."U_QdeInner"
	,T0."U_InnerAltura"
	,T0."U_InnerLargura"
	,T0."U_InnerComprimento"
	,T0."U_InnerPeso"
	,T0."U_InnerPesoLiq"
	,T0."U_MasterCodBarras"
	,T0."U_QdeMaster"
	,T0."U_MasterAltura"
	,T0."U_MasterLargura"
	,T0."U_MasterComprimento"
	,T0."U_MasterPeso"
	,T0."U_MasterPesoLiq"
	,T0."U_ItemComposicao" AS "InfoTecnicas"
	,T0."U_ItemCaract01" AS "Caracteristica_1"
	,T0."U_ItemCaract02" AS "Caracteristica_2"
	,T0."U_ItemCaract03" AS "Caracteristica_3"
	,T0."U_ItemCaract04" AS "Caracteristica_4"
	,T0."U_CVA_FlexyImagem" AS "URL_IMAGEM"
	,T0."U_NumInmetro" AS "INMETRO"
	,T0."U_ItemDesc" AS "Descricao_Adicional"
FROM "SBO_BRW_PRD"."OITM" T0
INNER JOIN ITM10 T1 ON T0."ItemCode" = T1."ItemCode"
INNER JOIN OCRY T2 ON T1."ISOriCntry" = T2."Code"
INNER JOIN ONCM T3 ON T0."NCMCode" = T3."AbsEntry"