// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PortalHelpdeskTI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250714175443_CorrigirRelacionamentoTipoCategoria")]
    partial class CorrigirRelacionamentoTipoCategoria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Anexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChamadoId")
                        .HasColumnType("int");

                    b.Property<int?>("InteracaoId")
                        .HasColumnType("int");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChamadoId");

                    b.HasIndex("InteracaoId");

                    b.ToTable("Anexos");
                });

            modelBuilder.Entity("Interacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChamadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChamadoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Interacoes");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.CategoriaChamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoChamadoId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoChamadoId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoChamadoId");

                    b.HasIndex("TipoChamadoId1");

                    b.ToTable("CategoriaChamado");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Chamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Solucao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubcategoriaId")
                        .HasColumnType("int");

                    b.Property<int?>("TecnicoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoChamadoId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId1")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId2")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId3")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId4")
                        .HasColumnType("int");

                    b.Property<bool>("VisualizadoPeloSolicitante")
                        .HasColumnType("bit");

                    b.Property<bool>("VisualizadoPeloTecnico")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("SubcategoriaId");

                    b.HasIndex("TecnicoId");

                    b.HasIndex("TipoChamadoId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioId1");

                    b.HasIndex("UsuarioId2");

                    b.HasIndex("UsuarioId3");

                    b.HasIndex("UsuarioId4");

                    b.ToTable("Chamados");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.SmtpConfiguracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FromEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmtpPass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("int");

                    b.Property<string>("SmtpServer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmtpUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SmtpConfiguracoes");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.SubcategoriaChamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("SubcategoriaChamado");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.TemplateEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CorpoHtml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TemplatesEmail");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.TipoChamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoChamado");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Anexo", b =>
                {
                    b.HasOne("PortalHelpdeskTI.Models.Chamado", "Chamado")
                        .WithMany("Anexos")
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Interacao", "Interacao")
                        .WithMany("Anexos")
                        .HasForeignKey("InteracaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Chamado");

                    b.Navigation("Interacao");
                });

            modelBuilder.Entity("Interacao", b =>
                {
                    b.HasOne("PortalHelpdeskTI.Models.Chamado", "Chamado")
                        .WithMany("Interacoes")
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalHelpdeskTI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chamado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.CategoriaChamado", b =>
                {
                    b.HasOne("PortalHelpdeskTI.Models.TipoChamado", "TipoChamado")
                        .WithMany()
                        .HasForeignKey("TipoChamadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortalHelpdeskTI.Models.TipoChamado", null)
                        .WithMany("Categorias")
                        .HasForeignKey("TipoChamadoId1");

                    b.Navigation("TipoChamado");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Chamado", b =>
                {
                    b.HasOne("PortalHelpdeskTI.Models.CategoriaChamado", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortalHelpdeskTI.Models.SubcategoriaChamado", "Subcategoria")
                        .WithMany()
                        .HasForeignKey("SubcategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortalHelpdeskTI.Models.Usuario", "Tecnico")
                        .WithMany()
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PortalHelpdeskTI.Models.TipoChamado", "TipoChamado")
                        .WithMany()
                        .HasForeignKey("TipoChamadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortalHelpdeskTI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortalHelpdeskTI.Models.Usuario", null)
                        .WithMany("Chamados")
                        .HasForeignKey("UsuarioId1");

                    b.HasOne("PortalHelpdeskTI.Models.Usuario", null)
                        .WithMany("ChamadosAssumidos")
                        .HasForeignKey("UsuarioId2");

                    b.HasOne("PortalHelpdeskTI.Models.Usuario", null)
                        .WithMany("ChamadosAtendidos")
                        .HasForeignKey("UsuarioId3");

                    b.HasOne("PortalHelpdeskTI.Models.Usuario", null)
                        .WithMany("ChamadosCriados")
                        .HasForeignKey("UsuarioId4");

                    b.Navigation("Categoria");

                    b.Navigation("Subcategoria");

                    b.Navigation("Tecnico");

                    b.Navigation("TipoChamado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.SubcategoriaChamado", b =>
                {
                    b.HasOne("PortalHelpdeskTI.Models.CategoriaChamado", "Categoria")
                        .WithMany("Subcategorias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Usuario", b =>
                {
                    b.HasOne("PortalHelpdeskTI.Models.Departamento", "Departamento")
                        .WithMany("Usuarios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("Interacao", b =>
                {
                    b.Navigation("Anexos");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.CategoriaChamado", b =>
                {
                    b.Navigation("Subcategorias");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Chamado", b =>
                {
                    b.Navigation("Anexos");

                    b.Navigation("Interacoes");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Departamento", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.TipoChamado", b =>
                {
                    b.Navigation("Categorias");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Usuario", b =>
                {
                    b.Navigation("Chamados");

                    b.Navigation("ChamadosAssumidos");

                    b.Navigation("ChamadosAtendidos");

                    b.Navigation("ChamadosCriados");
                });
#pragma warning restore 612, 618
        }
    }
}
