// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PortalHelpdeskTI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Anexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChamadoId")
                        .HasColumnType("int");

                    b.Property<int?>("InteracaoId")
                        .HasColumnType("int");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChamadoId");

                    b.HasIndex("InteracaoId");

                    b.ToTable("Anexos");
                });

            modelBuilder.Entity("Interacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChamadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChamadoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Interacoes");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.AvaliacaoChamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChamadoId")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ChamadoId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("AvaliacoesChamado", (string)null);
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.BaseConhecimentoIA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PalavraChave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sugestao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BaseConhecimentoIA");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.CategoriaChamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoChamadoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoChamadoId");

                    b.ToTable("CategoriaChamado");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Chamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AvaliacaoLembreteEnviado")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Solucao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("SubcategoriaId")
                        .HasColumnType("int");

                    b.Property<int?>("TecnicoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoChamadoId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId1")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId2")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId3")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId4")
                        .HasColumnType("int");

                    b.Property<bool>("VisualizadoPeloSolicitante")
                        .HasColumnType("bit");

                    b.Property<bool>("VisualizadoPeloTecnico")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("SubcategoriaId");

                    b.HasIndex("TecnicoId");

                    b.HasIndex("TipoChamadoId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioId1");

                    b.HasIndex("UsuarioId2");

                    b.HasIndex("UsuarioId3");

                    b.HasIndex("UsuarioId4");

                    b.ToTable("Chamados");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.ChamadoStatusLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChamadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ChamadoId", "DataHora" }, "IX_ChamadoStatusLogs_Cha_Data");

                    b.ToTable("ChamadoStatusLogs");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Comissoes.ComissaoAjuste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataIni")
                        .HasColumnType("date");

                    b.Property<string>("NFsRelacionadas")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SlpCode")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(19,6)");

                    b.HasKey("Id");

                    b.HasIndex("SlpCode", "DataIni", "DataFim");

                    b.ToTable("ComissaoAjuste", (string)null);
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Comissoes.ComissaoEnvioLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailPara")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Erro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<int>("SlpCode")
                        .HasColumnType("int");

                    b.Property<string>("SlpName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Sucesso")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ComissaoEnvioLogs");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Comissoes.ComissaoVendedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("BaseCalculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DestacarIR")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ParticipaRelatorio")
                        .HasColumnType("bit");

                    b.Property<decimal>("Percentual")
                        .HasColumnType("decimal(9,6)");

                    b.Property<int>("SlpCode")
                        .HasColumnType("int");

                    b.Property<string>("SlpName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("TipoVendedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SlpCode")
                        .IsUnique();

                    b.ToTable("ComissaoVendedor", null, t =>
                        {
                            t.HasTrigger("TR_ComissaoVendedor_Ativo_ForceParticipa");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.IntegracoesWmsDados.WmsProcesso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChaveItem")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<string>("ChaveProcesso")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ClienteFornecedor")
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("CodProprietario")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("CodigoProduto")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoProduto")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("NomeProprietario")
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("NumeroPedido")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)");

                    b.Property<decimal?>("QuantidadeDivergente")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("QuantidadeExecutada")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("QuantidadePrevista")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("StatusAnterior")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("UltimaSincronizacaoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsuarioResponsavel")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("DataReferencia");

                    b.HasIndex("NumeroDocumento");

                    b.HasIndex("NumeroPedido");

                    b.HasIndex("Tipo", "ChaveItem")
                        .IsUnique();

                    b.HasIndex("Tipo", "Status");

                    b.ToTable("WmsProcessos", (string)null);
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.IntegracoesWmsDados.WmsProcessoLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CamposAlteradosJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChaveItem")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<string>("ChaveProcesso")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Evento")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusAnterior")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("StatusNovo")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("WmsProcessoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Tipo", "ChaveProcesso");

                    b.HasIndex("WmsProcessoId", "CriadoEm");

                    b.ToTable("WmsProcessoLogs", (string)null);
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.IntegracoesWmsDados.WmsSyncExecucao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FimEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InicioEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensagem")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RegistrosAlterados")
                        .HasColumnType("int");

                    b.Property<int>("RegistrosNovos")
                        .HasColumnType("int");

                    b.Property<int>("RegistrosRecebidos")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Tipo", "InicioEm");

                    b.ToTable("WmsSyncExecucoes", (string)null);
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Inventario.EquipamentoInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnderecoIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("EnderecoMac")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Fabricante")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Hostname")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("NomeEquipamento")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrigemCadastro")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Patrimonio")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ProprietarioDepartamentoManual")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ProprietarioEmailManual")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("ProprietarioNomeManual")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int?>("ProprietarioUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("SistemaOperacional")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("UltimaDescobertaEm")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoIp");

                    b.HasIndex("EnderecoMac");

                    b.HasIndex("NumeroSerie");

                    b.HasIndex("Patrimonio");

                    b.HasIndex("ProprietarioUsuarioId");

                    b.ToTable("InventarioEquipamentos", (string)null);
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Inventario.InventarioAnexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaminhoRelativo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContentType")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipamentoInventarioId")
                        .HasColumnType("int");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EquipamentoInventarioId");

                    b.ToTable("InventarioAnexos", (string)null);
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.PalavraChaveIA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Termo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PalavrasChaveIA");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Permissoes.RelatorioCatalogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UrlVisualizar")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("RelatoriosCatalogo", (string)null);
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Permissoes.RelatorioPermissaoDepartamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<bool>("PodeVer")
                        .HasColumnType("bit");

                    b.Property<string>("RelatorioKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("RelatorioKey");

                    b.HasIndex("DepartamentoId", "RelatorioKey")
                        .IsUnique();

                    b.ToTable("RelatorioPermissaoDepartamento", (string)null);
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Permissoes.RelatorioPermissaoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("PodeVer")
                        .HasColumnType("bit");

                    b.Property<string>("RelatorioKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RelatorioKey");

                    b.HasIndex("UsuarioId", "RelatorioKey")
                        .IsUnique();

                    b.ToTable("RelatorioPermissaoUsuario", (string)null);
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Quizzes.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmbaralharQuestoes")
                        .HasColumnType("bit");

                    b.Property<decimal?>("NotaCortePercentual")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("Publicado")
                        .HasColumnType("bit");

                    b.Property<int?>("TempoLimiteSegundos")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Quizzes.QuizOpcao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Correta")
                        .HasColumnType("bit");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<int>("QuizQuestaoId")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuizQuestaoId");

                    b.ToTable("QuizOpcoes");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Quizzes.QuizQuestao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizQuestoes");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Quizzes.QuizResposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("QuizOpcaoId")
                        .HasColumnType("int");

                    b.Property<int>("QuizQuestaoId")
                        .HasColumnType("int");

                    b.Property<int>("QuizTentativaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizTentativaId");

                    b.ToTable("QuizRespostas");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Quizzes.QuizTentativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Fim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NotaPercentual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PontosMaximos")
                        .HasColumnType("int");

                    b.Property<int>("PontosObtidos")
                        .HasColumnType("int");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizTentativas");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.SLAConfiguracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int?>("SubcategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("TempoResolucaoHoras")
                        .HasColumnType("int");

                    b.Property<int>("TempoRespostaHoras")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("SubcategoriaId");

                    b.ToTable("SLAConfiguracoes", (string)null);
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.SmtpConfiguracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FromEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmtpPass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("int");

                    b.Property<string>("SmtpServer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmtpUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SmtpConfiguracoes");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.SubcategoriaChamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("SubcategoriaChamado");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.TemplateEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CorpoHtml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TemplatesEmail");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.TipoChamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoChamado");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmado")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ramal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenAtivacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TokenAtivacaoExpiraEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TokenExpiraEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenRedefinicaoSenha")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Anexo", b =>
                {
                    b.HasOne("PortalHelpdeskTI.Models.Chamado", "Chamado")
                        .WithMany("Anexos")
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Interacao", "Interacao")
                        .WithMany("Anexos")
                        .HasForeignKey("InteracaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Chamado");

                    b.Navigation("Interacao");
                });

            modelBuilder.Entity("Interacao", b =>
                {
                    b.HasOne("PortalHelpdeskTI.Models.Chamado", "Chamado")
                        .WithMany("Interacoes")
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalHelpdeskTI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chamado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.AvaliacaoChamado", b =>
                {
                    b.HasOne("PortalHelpdeskTI.Models.Chamado", "Chamado")
                        .WithMany()
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalHelpdeskTI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chamado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.CategoriaChamado", b =>
                {
                    b.HasOne("PortalHelpdeskTI.Models.TipoChamado", "TipoChamado")
                        .WithMany("Categorias")
                        .HasForeignKey("TipoChamadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoChamado");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Chamado", b =>
                {
                    b.HasOne("PortalHelpdeskTI.Models.CategoriaChamado", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortalHelpdeskTI.Models.SubcategoriaChamado", "Subcategoria")
                        .WithMany()
                        .HasForeignKey("SubcategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortalHelpdeskTI.Models.Usuario", "Tecnico")
                        .WithMany()
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PortalHelpdeskTI.Models.TipoChamado", "TipoChamado")
                        .WithMany()
                        .HasForeignKey("TipoChamadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortalHelpdeskTI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortalHelpdeskTI.Models.Usuario", null)
                        .WithMany("Chamados")
                        .HasForeignKey("UsuarioId1");

                    b.HasOne("PortalHelpdeskTI.Models.Usuario", null)
                        .WithMany("ChamadosAssumidos")
                        .HasForeignKey("UsuarioId2");

                    b.HasOne("PortalHelpdeskTI.Models.Usuario", null)
                        .WithMany("ChamadosAtendidos")
                        .HasForeignKey("UsuarioId3");

                    b.HasOne("PortalHelpdeskTI.Models.Usuario", null)
                        .WithMany("ChamadosCriados")
                        .HasForeignKey("UsuarioId4");

                    b.Navigation("Categoria");

                    b.Navigation("Subcategoria");

                    b.Navigation("Tecnico");

                    b.Navigation("TipoChamado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.ChamadoStatusLog", b =>
                {
                    b.HasOne("PortalHelpdeskTI.Models.Chamado", "Chamado")
                        .WithMany()
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chamado");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.IntegracoesWmsDados.WmsProcessoLog", b =>
                {
                    b.HasOne("PortalHelpdeskTI.Models.IntegracoesWmsDados.WmsProcesso", "WmsProcesso")
                        .WithMany("Logs")
                        .HasForeignKey("WmsProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WmsProcesso");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Inventario.EquipamentoInventario", b =>
                {
                    b.HasOne("PortalHelpdeskTI.Models.Usuario", "ProprietarioUsuario")
                        .WithMany()
                        .HasForeignKey("ProprietarioUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ProprietarioUsuario");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Inventario.InventarioAnexo", b =>
                {
                    b.HasOne("PortalHelpdeskTI.Models.Inventario.EquipamentoInventario", "EquipamentoInventario")
                        .WithMany("Anexos")
                        .HasForeignKey("EquipamentoInventarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipamentoInventario");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Permissoes.RelatorioPermissaoDepartamento", b =>
                {
                    b.HasOne("PortalHelpdeskTI.Models.Departamento", null)
                        .WithMany()
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalHelpdeskTI.Models.Permissoes.RelatorioCatalogo", null)
                        .WithMany()
                        .HasForeignKey("RelatorioKey")
                        .HasPrincipalKey("Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Permissoes.RelatorioPermissaoUsuario", b =>
                {
                    b.HasOne("PortalHelpdeskTI.Models.Permissoes.RelatorioCatalogo", null)
                        .WithMany()
                        .HasForeignKey("RelatorioKey")
                        .HasPrincipalKey("Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalHelpdeskTI.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Quizzes.QuizOpcao", b =>
                {
                    b.HasOne("PortalHelpdeskTI.Models.Quizzes.QuizQuestao", "Questao")
                        .WithMany("Opcoes")
                        .HasForeignKey("QuizQuestaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questao");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Quizzes.QuizQuestao", b =>
                {
                    b.HasOne("PortalHelpdeskTI.Models.Quizzes.Quiz", "Quiz")
                        .WithMany("Questoes")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Quizzes.QuizResposta", b =>
                {
                    b.HasOne("PortalHelpdeskTI.Models.Quizzes.QuizTentativa", "Tentativa")
                        .WithMany()
                        .HasForeignKey("QuizTentativaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tentativa");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Quizzes.QuizTentativa", b =>
                {
                    b.HasOne("PortalHelpdeskTI.Models.Quizzes.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.SLAConfiguracao", b =>
                {
                    b.HasOne("PortalHelpdeskTI.Models.CategoriaChamado", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalHelpdeskTI.Models.SubcategoriaChamado", "Subcategoria")
                        .WithMany()
                        .HasForeignKey("SubcategoriaId");

                    b.Navigation("Categoria");

                    b.Navigation("Subcategoria");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.SubcategoriaChamado", b =>
                {
                    b.HasOne("PortalHelpdeskTI.Models.CategoriaChamado", "Categoria")
                        .WithMany("Subcategorias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Usuario", b =>
                {
                    b.HasOne("PortalHelpdeskTI.Models.Departamento", "Departamento")
                        .WithMany("Usuarios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("Interacao", b =>
                {
                    b.Navigation("Anexos");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.CategoriaChamado", b =>
                {
                    b.Navigation("Subcategorias");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Chamado", b =>
                {
                    b.Navigation("Anexos");

                    b.Navigation("Interacoes");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Departamento", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.IntegracoesWmsDados.WmsProcesso", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Inventario.EquipamentoInventario", b =>
                {
                    b.Navigation("Anexos");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Quizzes.Quiz", b =>
                {
                    b.Navigation("Questoes");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Quizzes.QuizQuestao", b =>
                {
                    b.Navigation("Opcoes");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.TipoChamado", b =>
                {
                    b.Navigation("Categorias");
                });

            modelBuilder.Entity("PortalHelpdeskTI.Models.Usuario", b =>
                {
                    b.Navigation("Chamados");

                    b.Navigation("ChamadosAssumidos");

                    b.Navigation("ChamadosAtendidos");

                    b.Navigation("ChamadosCriados");
                });
#pragma warning restore 612, 618
        }
    }
}
